title: Using Python Tuples
hero_image: images/banner.png
description: generic-python-tuples description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
duration: 1 
ingredient: true
listed: false
steps:
  - title: Tuples
