title: Using Python Tuples
hero_image: images/banner.png
description: how to use tuples in Python
original_url:
theme: cc-prototype
duration: 1
listed: false
ingredient: true
copyedit: false
interests:
technologies: "python"
steps:
  - title: Tuples
